= Tridash Examples =

This page contains brief examples of Tridash applications aiming to
demonstrate the language's functionality. This page is not a tutorial
of the language. For an introductory tutorial head to
link:tutorials/[Introductory Tutorials].

Each example is accompanied by a live demo of the program.

== Adding Numbers ==

The following is an example of an application consisting of two text
input fields, which displays the sum of the two numbers below the
fields. The sum is recomputed, whenever the values of one of the text
fields is changed by the user.

In most of today's languages this would require setting up event
listeners, and callback functions for each of the text fields, you'd
then have to update a `sum` variable and manually change displayed
value to the new sum. With Tridash, the entire application can be
implemented with just the following:

--------------------------------------------------
<? /import(core) ?>

<!doctype html>
<html>
  <body>
    <div><label>A:<br/><input value="<?@ to-int(a) ?>" /></label></div>
    <div><label>B:<br/><input value="<?@ to-int(b) ?>" /></label></div>
    <p>A + B = <?@ a + b ?></p>
  </body>
</html>
--------------------------------------------------

++++++++++++++++++++++++++++++++++++++++++++++++++
<div style="text-align: center"><iframe src="examples/sum.html"></iframe></div>
++++++++++++++++++++++++++++++++++++++++++++++++++

== Conditions ==

Let's say you'd like to enhance the previous application, so that the
user is informed when the sum of the numbers exceeds a limit, which is
also given by the user.

--------------------------------------------------
<?
 /import(core)

 sum <- a + b
?>

<!doctype html>
<html>
    <body>
      <div><label>Limit:<br/><input value="<?@ to-int(limit) ?>"/></label></div>
      <div><label>A:<br/><input value="<?@ to-int(a) ?>" /></label></div>
      <div><label>B:<br/><input value="<?@ to-int(b) ?>" /></label></div>
      <p>A + B = <?@ sum ?></p>
      <p>
       <?@
        case(
            sum <= limit : "Within Limit!",
            "Limit Exceeded!"
        )
       ?>
      </p>
    </body>
</html>
--------------------------------------------------

++++++++++++++++++++++++++++++++++++++++++++++++++
<div style="text-align: center">
<iframe src="examples/limit.html" height="200"></iframe>
</div>
++++++++++++++++++++++++++++++++++++++++++++++++++

Implementing the new functionality was almost as easy as adding new UI
elements. The `case( ... )` expression chooses the message ``Within
Limit!'' or ``Limit exceeded!'' based on whether the sum is less than
or equal to limit.
