= Tridash =

Tridash is a programming language which aims to make the development
of interactive applications easier and less error-prone.

== How's it Different ==

What sets Tridash apart from the popular languages of today is that it
is designed from the ground up for developing applications which
respond to user interaction and events, whereas most programming
languages, particularly imperative programming languages are
originally designed for developing batch-style applications which
perform their task and then exit without interacting with the user. As
a result developing interactive applications with these languages, is
difficult and prone to bugs.

In Tridash an application is composed of a set of stateful
computational components called nodes. Each node has a particular
value, which is computed from a function of one or more dependency
nodes. When the values of a node's dependency nodes changes, the
node's value is automatically recomputed. Nodes can either be purely
computational components or can be bound to the state of a user
interface element, the network or the file system. For example a node
can be bound to the value of a text field UI element.

With Tridash you can focus on the core logic of your application code,
by expressing the application state as a set of dependencies between
components. This is contrary to the approach taken by most languages
where your application is expressed as a linear sequence of
instructions, in which it is up to the programmer to manually manage
the application state correctly.

Visit link:philosophy.html[Philosophy], if you'd like to read on about
the philosophy of the language.

== Getting Started ==

Visit link:installation.html[Installation] for the download links and
installation instructions for the platform of your choice.

=== Tutorials ===

link:tutorials/[Introductory Tutorials]:: Introduces the core concepts
of the language and gradually moves on to more advanced features

.Alternative Formats
- link:tutorials.pdf[PDF]
- link:tutorials-single.html[Single Page HTML]


== Documentation ==

link:manual[Reference Manual]:: Documents the syntax, semantics,
features and core modules of the language.

.Alternative Formats
- link:tridash.pdf[PDF]
- link:tridash-single.html[Single Page HTML]

The Linux and OS X/macOS distributions contain the full manual in the
'Info' format.

The Windows distribution contains the full manual in the Compiled HTML
Help format.

== Examples ==

Visit link:examples.html[Examples] for live examples of Tridash
applications.

== Support ==

[small]#If you find this project interesting and would like to ensure
its continued development please consider making a donation via
link:https://www.patreon.com/alexgutev[Patreon]#
